// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/gm3yaWithFB/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/gm3yaWithFB/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('c:/gm3yaWithFB/index.ios.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('myrnapp', appParameters);
});